import { Inter } from "next/font/google";

import { Layout } from "@/components/Layout";
import { ProductsProvider } from "@/hooks/useProducts";
import "./globals.css";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsProvider>
          <Layout>{children}</Layout>
          <Modal />
        </ProductsProvider>
      </body>
    </html>
  );
}
